### ISSUE TITLE
Question about the rate of change

### ISSUE THREAD

**Issue by khywjt** [mdibiase1/Predict_Rate_of_Change#1]
In the step One the rate of change is defined as rate =  (y2-y1)./(age2-age1) but in the paper the rate is the (%/year), how to understand the differences.
And if the rate is negative, the gamlss model will report error, it seems that BCT can not handle the negative input, how can I deal with the error?

**Comment by mdibiase1** [comment]
I computed both raw rates of change and percent change.

Try adding 500 to the values before running gamlss. Then subtract 500 from the outputs yielded.

Thanks,

Maria

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: khywjt ***@***.***>
Sent: Saturday, June 17, 2023 12:26:06 AM
To: mdibiase1/Predict_Rate_of_Change ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mdibiase1/Predict_Rate_of_Change] Question about the rate of change (Issue #1)


        External Email - Use Caution

In the step One the rate of change is defined as rate = (y2-y1)./(age2-age1) but in the paper the rate is the (%/year), how to understand the differences.
And if the rate is negative, the gamlss model will report error, it seems that BCT can not handle the negative input, how can I deal with the error?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Q6AM_xxwLWyWYJEkBY0vJsTrmWGgLryRKZOQBoZ_tUGmduEplhuuqhOQ-sYnEixWiO-5SQ1ZGPsmXBZlONRgfzsg5rpvet2FemxW7iPvqhh1yuGfgWa-x43_5IvhyHgXN1adlPWVrkp0Mu7Kf5AYDdyqSy2Kgm6cm1pbSbH_2WNOAIJj09efgOIgtX8O6fbDH2T4B0SI5LHpmVhmsY-5kcKz4PD181_Rfgq5PbwSYteRZUk9ZK81qXHokydOBQ8a5p7jXcPVViHzvI3Xm96IF59Ge8yJMd_5ZqsZGM28KFQtVH5uGomQoQodWPwbOLJc/https%3A%2F%2Fgithub.com%2Fmdibiase1%2FPredict_Rate_of_Change%2Fissues%2F1>, or unsubscribe<https://secure-web.cisco.com/13RVajs72oBJSe0BO6k-EHjrN_pNaezMs14hNYz7BNP4iGYBCpErRsGphBzk8KNm488lfYbxMSr3mbvepWSziL7oZQkD7yaezfgP-SZl4pv7oOlR4ZQmS8tTOn9j2M7ygU8MtBQJpfSuPI-jmDt-XDvOPFfS6lH9GVnoBDI0FLcD5lQR7_49526QnPoVNr62KXcitiC1c6ao_eyGr8jXONfVSQo1gmJ2vlOmZ5g49dL8go1lEHwVBt8hV8lDntJrww3-vFJxTyZBUEQ1oxm_DNhOge5ta6ooG2SVcQDp1pxLmsGd8GGdP0VeF3-h44Ksf/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALYHETEH5YMZIDMANDT3MZDXLRUH5ANCNFSM6AAAAAAZJKXVEA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by khywjt** [comment]
thanks a lot
