### ISSUE TITLE
Does this model allow analysis of different quantities of cross-sectional and longitudinal data?

### ISSUE THREAD

**Issue by khywjt** [mdibiase1/Predict_Rate_of_Change#2]
I have some data that exists only at a single time point but belongs to the same cohort. Can I include this data in the cross-analysis as well?

**Comment by mdibiase1** [comment]
This is of course possible - doing so depends on your research question. For my analysis, I used the same individuals at baseline and to yield rates of change.

From: khywjt ***@***.***>
Date: Tuesday, June 20, 2023 at 10:28 AM
To: mdibiase1/Predict_Rate_of_Change ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mdibiase1/Predict_Rate_of_Change] Does this model allow analysis of different quantities of cross-sectional and longitudinal data? (Issue #2)

        External Email - Use Caution

I have some data that exists only at a single time point but belongs to the same cohort. Can I include this data in the cross-analysis as well?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1xavqj0jC_T66VPezjMkcZcvQiG-le2vo4HG-67pNX8uxgZZ7kXum1jqA53Yhz6xnhwE1bFlaqP-cA6R8quvL7MfC5N--s_C_hTdIf8VfvDxVuNZdYZ9c5llQsqNsp5EzvaEThmuJIv9gWZK_U7onm6A-1YvhzcfwzOg8BnmytTHzydYxyUsaPCZavyDLh0UKxHg4TWug5KpOTNW4iVp1-v-L1T5yhiJJmXrpCIGuDanfdFZ3K_l7U9aYfaB4SIRg9nUJnyLXj9oCnRFwhReUb6KSPHg7MHbiMqNsSp1kVeR4IyaAJw0bY_q2eL1-8ZkVk0ya6IkNhHKRfZl4x6I65g/https%3A%2F%2Fgithub.com%2Fmdibiase1%2FPredict_Rate_of_Change%2Fissues%2F2>, or unsubscribe<https://secure-web.cisco.com/1Q6p8ULOSuHpBZF1-XtGZIIS-93m4Z5bWjA7uzMXMdoDZC1vkC0GscPwkWM_IqYYWUVEEMClI9WXXT55Bo400gvNX2KqaHLX0oWKR15NDDhXaokkX9mVoPMWW1UGP9G5xDfoalITaavb5P2EnU8P6oFInDjOM45rfruOtiRb08MVVJQIHTAwL1dselD_fZARMAJLYR9otisn7VSskzT25Ea_BWBlTRyFQw4zJhTYoRoVk2gVd7MuYY7h6anz2S_OdI2UDwo2OCVYM2uFLAq2bBOrLNywpyDJjkCEsqCgafNNiBiSzdBbToMcpWxKoQASarKtD5nml_EQ004Q7fCyzZg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALYHETF3WQRM7QPE7OHCYXLXMDVBRANCNFSM6AAAAAAZMRBW4Q>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by khywjt** [comment]
Thank you very much for your response. It has been very helpful to me.
